name: 'CI'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'

      - name: 'Build docker image'
        run: 'npm run build:docker'

      - name: 'Install the dependencies'
        run: 'npm install'

      - name: 'Test smart contracts'
        run: 'npm run test'

      - name: 'Integration test'
        run: 'npm run test-i9n'
