name: 'CI'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # v3

      - name: 'Install Node.js'
        uses: 'actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7' # v3

      - name: 'Build docker image'
        run: 'npm run build:docker'

      - name: 'Install the dependencies and compile smart contracts'
        run: 'npm install && npm run compile'

      - name: 'Test smart contracts'
        run: 'npm run test'

      - name: 'Integration test'
        run: 'npm run test-i9n'
