name: Publish to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: 'Install Node.js'
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@waveshq'
      - name: Install dependencies and compile smart contracts
        run: npm ci && npm run compile
      - name: Build the package
        run: npm run build
      - run: npm config set "//registry.npmjs.org/:_authToken" "\${NODE_AUTH_TOKEN}" --location=project
      - name: Publish package on NPM 📦
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WAVESHQ_NPM_TOKEN }}
      - run: npm config delete "//registry.npmjs.org/:_authToken" --location=project
        if: always()
