name: Publish to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repo'
        uses: actions/checkout@v3
      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
        with:
          node-version-file: '.nvmrc'
      - name: Build the package
        run: npm run build
        with:
          node-version-file: '.nvmrc'
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WAVESHQ_NPM_TOKEN }}
